# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directories:
      - "/" # Location of package manifests
      - "/Boardlight"
      - "/Backboard"
    schedule:
      interval: "weekly"

  - package-ecosystem: "dotnet-sdk" # See documentation for possible values
    directory: "/Blueboard" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/Backboard/src-tauri" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
