/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthResetPasswordRequestBody {
    #[serde(rename = "newPassword")]
    pub new_password: String,
}

impl AuthResetPasswordRequestBody {
    pub fn new(new_password: String) -> AuthResetPasswordRequestBody {
        AuthResetPasswordRequestBody {
            new_password,
        }
    }
}

