/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShopIndexOwnLolosResponse {
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<i32>,
    #[serde(rename = "coins", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub coins: Option<Option<Vec<models::ShopIndexOwnLolosResponseCoin>>>,
}

impl ShopIndexOwnLolosResponse {
    pub fn new() -> ShopIndexOwnLolosResponse {
        ShopIndexOwnLolosResponse {
            balance: None,
            coins: None,
        }
    }
}

