/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShopUpdateQrCodeRequestBody {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "email")]
    pub email: String,
}

impl ShopUpdateQrCodeRequestBody {
    pub fn new(name: String, email: String) -> ShopUpdateQrCodeRequestBody {
        ShopUpdateQrCodeRequestBody {
            name,
            email,
        }
    }
}

